"""
Référentiel officiel des 52+ Agences Immobilières de Nouvelle-Calédonie.
Permet d'identifier, normaliser et catégoriser les agences professionnelles
qui syndiquent leurs biens sur api.immobilier.nc, bienmeloger.nc ou en direct.
"""

from typing import Dict, Any, List, Optional
import re

NC_AGENCIES: List[Dict[str, Any]] = [
    {
        "id": "soleil",
        "name": "Agence Soleil",
        "aliases": ["agence soleil", "agencesoleil", "soleil.nc"],
        "website": "https://www.soleil.nc",
        "city": "Nouméa",
        "domains": ["soleil.nc"],
        "logo_text": "SOLEIL",
        "badge_color": "amber",
    },
    {
        "id": "diot",
        "name": "Diot Immobilier",
        "aliases": ["diot", "diot immobilier", "diot.nc"],
        "website": "https://diot.nc",
        "city": "Nouméa",
        "domains": ["diot.nc"],
        "logo_text": "DIOT",
        "badge_color": "blue",
    },
    {
        "id": "promobat",
        "name": "Promobat",
        "aliases": ["promobat", "promobat .", "promobat.nc"],
        "website": "https://www.promobat.nc",
        "city": "Nouméa",
        "domains": ["promobat.nc"],
        "logo_text": "PROMOBAT",
        "badge_color": "red",
    },
    {
        "id": "maximmo",
        "name": "Max Immo",
        "aliases": ["max immo", "maximmo", "maximmo.nc"],
        "website": "https://www.maximmo.nc",
        "city": "Nouméa & Grand Nouméa",
        "domains": ["maximmo.nc"],
        "logo_text": "MAXIMMO",
        "badge_color": "pink",
    },
    {
        "id": "caillard_kaddour",
        "name": "Caillard & Kaddour",
        "aliases": ["caillard & kaddour", "caillard et kaddour", "ck immo"],
        "website": "https://www.caillard-kaddour.com",
        "city": "Nouméa & Brousse",
        "domains": ["caillard-kaddour.com", "ck.nc"],
        "logo_text": "C&K",
        "badge_color": "rose",
    },
    {
        "id": "noumea_immo",
        "name": "Nouméa Immobilier",
        "aliases": ["nouméa immobilier", "noumea immobilier", "noumea-immobilier.nc"],
        "website": "https://www.noumeaimmobilier.nc",
        "city": "Nouméa",
        "domains": ["noumea-immobilier.nc"],
        "logo_text": "NOUMÉA IMMO",
        "badge_color": "sky",
    },
    {
        "id": "alert_immo",
        "name": "Alert'Immo",
        "aliases": ["alert'immo", "alert immo", "alertimmo.nc"],
        "website": "https://alertimmo.nc",
        "city": "Mont-Dore & Nouméa",
        "domains": ["alertimmo.nc"],
        "logo_text": "ALERT'IMMO",
        "badge_color": "orange",
    },
    {
        "id": "le_cafe_immo",
        "name": "Le Café Immobilier",
        "aliases": ["le café immobilier", "le cafe immobilier", "lecafeimmobilier.nc"],
        "website": "https://www.lecafeimmobilier.nc",
        "city": "Nouméa",
        "domains": ["lecafeimmobilier.nc"],
        "logo_text": "CAFÉ IMMO",
        "badge_color": "stone",
    },
    {
        "id": "faubourg",
        "name": "Agence du Faubourg",
        "aliases": ["agence du faubourg", "du faubourg agence", "adf.nc"],
        "website": "https://www.adf.nc",
        "city": "Nouméa",
        "domains": ["adf.nc"],
        "logo_text": "FAUBOURG",
        "badge_color": "indigo",
    },
    {
        "id": "immonord",
        "name": "Agence Immonord",
        "aliases": ["agence immonord", "immonord agence", "immonord.nc", "immonord"],
        "website": "https://www.immonord.nc",
        "city": "Koumac & Koné",
        "domains": ["immonord.nc"],
        "logo_text": "IMMONORD",
        "badge_color": "teal",
    },
    {
        "id": "immo_plus",
        "name": "Immo Plus",
        "aliases": ["immo plus", "immo-plus", "immo-plus.nc"],
        "website": "https://www.immo-plus.nc",
        "city": "Nouméa",
        "domains": ["immo-plus.nc"],
        "logo_text": "IMMO+",
        "badge_color": "cyan",
    },
    {
        "id": "dclic_immo",
        "name": "D'Clic Immo",
        "aliases": ["d'clic immo", "d'clic immo paita", "dclicimmo.nc"],
        "website": "https://www.dclicimmo.nc",
        "city": "Païta & Nouméa",
        "domains": ["dclicimmo.nc"],
        "logo_text": "D'CLIC",
        "badge_color": "emerald",
    },
    {
        "id": "bien_immo",
        "name": "Bien-Immo",
        "aliases": ["bien-immo", "bienimmo", "bienimmo.agence"],
        "website": "https://www.bien-immo.nc",
        "city": "Nouméa & Dumbéa",
        "domains": ["bien-immo.nc", "gmail.com"],
        "logo_text": "BIEN-IMMO",
        "badge_color": "blue",
    },
    {
        "id": "acti_immo",
        "name": "Acti Immobilier",
        "aliases": ["acti immo", "acti immobilier", "acti-immo.nc"],
        "website": "https://www.acti-immo.nc",
        "city": "Nouméa & Grand Nouméa",
        "domains": ["acti-immo.nc"],
        "logo_text": "ACTI",
        "badge_color": "purple",
    },
    {
        "id": "chatelin",
        "name": "Chatelin Immobilier",
        "aliases": ["chatelin immobilier", "chatelin immo", "chatelin"],
        "website": "https://www.chatelin-immobilier.nc",
        "city": "Nouméa",
        "domains": ["chatelin-immobilier.nc"],
        "logo_text": "CHATELIN",
        "badge_color": "slate",
    },
    {
        "id": "tropic_immo",
        "name": "Tropic Immobilier",
        "aliases": ["tropic immobilier", "tropic immo"],
        "website": "https://www.tropicimmobilier.nc",
        "city": "Nouméa",
        "domains": ["tropicimmobilier.nc"],
        "logo_text": "TROPIC",
        "badge_color": "red",
    },
    {
        "id": "top_immo",
        "name": "Top Immo",
        "aliases": ["top immo", "top-immo"],
        "website": "https://www.topimmo.nc",
        "city": "Nouméa & Grand Nouméa",
        "domains": ["topimmo.nc"],
        "logo_text": "TOP IMMO",
        "badge_color": "red",
    },
    {
        "id": "open_immo",
        "name": "Open Immobilier",
        "aliases": ["open immobilier", "open immo"],
        "website": "https://www.open-immobilier.nc",
        "city": "Nouméa",
        "domains": ["open-immobilier.nc"],
        "logo_text": "OPEN",
        "badge_color": "sky",
    },
    {
        "id": "casa_immo",
        "name": "Casa Immo",
        "aliases": ["casa immo", "casa immo agence", "casaimmo.nc"],
        "website": "https://www.casaimmo.nc",
        "city": "Nouméa",
        "domains": ["casaimmo.nc"],
        "logo_text": "CASA IMMO",
        "badge_color": "amber",
    },
    {
        "id": "antoine",
        "name": "L'Agence d'Antoine",
        "aliases": ["l'agence d'antoine", "agence d'antoine"],
        "website": "https://www.agencedantoine.nc",
        "city": "Nouméa",
        "domains": ["agencedantoine.nc"],
        "logo_text": "ANTOINE",
        "badge_color": "teal",
    },
    {
        "id": "lagence_immo",
        "name": "L'Agence Immo",
        "aliases": ["l'agence immo", "l'agence immo info", "lagenceimmo.nc"],
        "website": "https://www.lagenceimmo.nc",
        "city": "Nouméa",
        "domains": ["lagenceimmo.nc"],
        "logo_text": "L'AGENCE",
        "badge_color": "yellow",
    },
    {
        "id": "luxury_immo",
        "name": "Luxury Immobilier",
        "aliases": ["luxury immobilier", "luxury immo"],
        "website": "https://www.luxury-immobilier.nc",
        "city": "Nouméa Baie des Citrons",
        "domains": ["luxury-immobilier.nc"],
        "logo_text": "LUXURY",
        "badge_color": "violet",
    },
    {
        "id": "alliance_immo",
        "name": "Alliance Immo",
        "aliases": ["alliance immo", "alliance immobilier"],
        "website": "https://www.allianceimmo.nc",
        "city": "Nouméa",
        "domains": ["allianceimmo.nc"],
        "logo_text": "ALLIANCE",
        "badge_color": "cyan",
    },
    {
        "id": "sunset_immo",
        "name": "Sunset Immobilier",
        "aliases": ["sunset immobilier", "sunset immo"],
        "website": "https://www.sunset-immobilier.nc",
        "city": "Nouméa",
        "domains": ["sunset-immobilier.nc"],
        "logo_text": "SUNSET",
        "badge_color": "amber",
    },
    {
        "id": "colardeau",
        "name": "Colardeau Agent Immobilier",
        "aliases": ["colardeau agent immobilier", "colardeau", "colardeau immo"],
        "website": "https://www.colardeau-immo.nc",
        "city": "Nouméa",
        "domains": ["colardeau-immo.nc"],
        "logo_text": "COLARDEAU",
        "badge_color": "zinc",
    },
    {
        "id": "lacroix",
        "name": "Cabinet Lacroix",
        "aliases": ["cabinet lacroix", "lacroix immobilier", "lacroix"],
        "website": "https://www.lacroix-immobilier.nc",
        "city": "Nouméa",
        "domains": ["lacroix.nc"],
        "logo_text": "LACROIX",
        "badge_color": "blue",
    },
    {
        "id": "agence_generale",
        "name": "L'Agence Générale",
        "aliases": ["l'agence générale", "agence generale", "agence générale"],
        "website": "https://www.agencegenerale.nc",
        "city": "Nouméa",
        "domains": ["agencegenerale.nc"],
        "logo_text": "GÉNÉRALE",
        "badge_color": "slate",
    },
    {
        "id": "az_immo",
        "name": "AZ Immo",
        "aliases": ["az immo", "az immobilier", "l'immobilier de a à z"],
        "website": "https://www.azimmo.nc",
        "city": "Nouméa",
        "domains": ["azimmo.nc"],
        "logo_text": "AZ IMMO",
        "badge_color": "amber",
    },
    {
        "id": "investiss_immo",
        "name": "Investiss' Immo",
        "aliases": ["investiss' immo", "investiss immo", "investissimmo"],
        "website": "https://www.investiss-immo.nc",
        "city": "Nouméa",
        "domains": ["investissimmo.nc", "lagoon.nc"],
        "logo_text": "INVESTISS'",
        "badge_color": "indigo",
    },
    {
        "id": "plein_sud",
        "name": "Plein Sud Immobilier",
        "aliases": ["plein sud immobilier", "plein-sud immobilier", "plein sud"],
        "website": "https://www.pleinsudimmobilier.nc",
        "city": "Mont-Dore & Nouméa",
        "domains": ["pleinsudimmobilier.nc"],
        "logo_text": "PLEIN SUD",
        "badge_color": "sky",
    },
    {
        "id": "sic",
        "name": "SIC (Bailleur Calédonien)",
        "aliases": ["sic", "société immobilière de calédonie"],
        "website": "https://www.sic.nc",
        "city": "Nouvelle-Calédonie",
        "domains": ["sic.nc"],
        "logo_text": "SIC",
        "badge_color": "emerald",
    },
    {
        "id": "fsh",
        "name": "Fonds Social de l'Habitat (FSH)",
        "aliases": ["fsh", "fonds social de l'habitat", "fond social de l'habitat"],
        "website": "https://www.fsh.nc",
        "city": "Nouvelle-Calédonie",
        "domains": ["fsh.nc"],
        "logo_text": "FSH",
        "badge_color": "blue",
    },
    {
        "id": "secal",
        "name": "SECAL",
        "aliases": ["secal", "sem secal"],
        "website": "https://www.secal.nc",
        "city": "Nouméa",
        "domains": ["secal.nc"],
        "logo_text": "SECAL",
        "badge_color": "teal",
    },
    {
        "id": "berode_ollivaud",
        "name": "Bérode & Ollivaud",
        "aliases": ["bérode & ollivaud", "berode & ollivaud", "berode"],
        "website": "https://www.berode-ollivaud.nc",
        "city": "Nouméa",
        "domains": ["berode.nc"],
        "logo_text": "BÉRODE",
        "badge_color": "rose",
    },
    {
        "id": "ellipse_immo",
        "name": "Ellipse Immo (Nord)",
        "aliases": ["ellipse immo", "ellipseimmo", "ellipse immo nord"],
        "website": "https://www.ellipseimmo.nc",
        "city": "Koné & Grand Nord",
        "domains": ["ellipseimmo.nc"],
        "logo_text": "ELLIPSE",
        "badge_color": "orange",
    },
    {
        "id": "trois_r",
        "name": "3R Immobilier",
        "aliases": ["3r immobilier", "3r immo", "3r"],
        "website": "https://www.3r-immobilier.nc",
        "city": "Nouméa",
        "domains": ["3r-immobilier.nc"],
        "logo_text": "3R IMMO",
        "badge_color": "cyan",
    },
    {
        "id": "isis_gestion",
        "name": "ISIS Gestion",
        "aliases": ["isis gestion", "isis"],
        "website": "https://www.isisgestion.nc",
        "city": "Nouméa",
        "domains": ["isisgestion.nc"],
        "logo_text": "ISIS",
        "badge_color": "yellow",
    },
    {
        "id": "my_home",
        "name": "My Home Immobilier",
        "aliases": ["my home immobilier", "my home immo"],
        "website": "https://www.myhomeimmobilier.nc",
        "city": "Nouméa",
        "domains": ["myhomeimmobilier.nc"],
        "logo_text": "MY HOME",
        "badge_color": "emerald",
    },
    {
        "id": "geron_immo",
        "name": "Geron'Immo",
        "aliases": ["geron'immo", "geron immo", "geronimmo"],
        "website": "https://www.geronimmo.nc",
        "city": "Nouméa",
        "domains": ["geronimmo.nc"],
        "logo_text": "GERON",
        "badge_color": "red",
    },
    {
        "id": "ab_immo",
        "name": "AB Immobilier",
        "aliases": ["ab immobilier", "a-b immobilier", "ab immo"],
        "website": "https://www.ab-immobilier.nc",
        "city": "Nouméa",
        "domains": ["ab-immobilier.nc"],
        "logo_text": "AB IMMO",
        "badge_color": "slate",
    },
    {
        "id": "local_immo",
        "name": "Local Immo",
        "aliases": ["local immo", "localimmo"],
        "website": "https://www.localimmo.nc",
        "city": "Nouméa",
        "domains": ["localimmo.nc"],
        "logo_text": "LOCAL IMMO",
        "badge_color": "zinc",
    },
    {
        "id": "caledonienne_immo",
        "name": "Calédonienne d'Immobilier",
        "aliases": ["calédonienne d'immobilier", "caledonienne d'immobilier"],
        "website": "https://www.caledonienne-immobilier.nc",
        "city": "Nouméa",
        "domains": ["caledonienne-immobilier.nc"],
        "logo_text": "CALÉDONIENNE",
        "badge_color": "red",
    },
    {
        "id": "data_immo",
        "name": "Data Immobilier",
        "aliases": ["data immobilier", "data immo"],
        "website": "https://www.data-immobilier.nc",
        "city": "Nouméa",
        "domains": ["data-immobilier.nc"],
        "logo_text": "DATA IMMO",
        "badge_color": "emerald",
    },
    {
        "id": "innov_immo",
        "name": "Innov'Immo Gestion",
        "aliases": ["innov'immo", "innovimmo", "innov'immo gestion"],
        "website": "https://www.innovimmo.nc",
        "city": "Nouméa",
        "domains": ["innovimmo.nc"],
        "logo_text": "INNOV'IMMO",
        "badge_color": "amber",
    },
    {
        "id": "a_vendre_nc",
        "name": "A Vendre Immobilier NC",
        "aliases": ["a vendre immobilier nc", "avendre immobilier"],
        "website": "https://www.avendre-immobilier.nc",
        "city": "Nouméa",
        "domains": ["avendre-immobilier.nc"],
        "logo_text": "À VENDRE NC",
        "badge_color": "green",
    },
    {
        "id": "immo_sud",
        "name": "Immo Sud",
        "aliases": ["immo sud", "immosud"],
        "website": "https://www.immosud.nc",
        "city": "Nouméa & Mont-Dore",
        "domains": ["immosud.nc"],
        "logo_text": "IMMO SUD",
        "badge_color": "rose",
    },
    {
        "id": "medihome",
        "name": "Medi Home",
        "aliases": ["medi home", "medihome"],
        "website": "https://www.medihome.nc",
        "city": "Dumbéa Sur Mer / Médipôle",
        "domains": ["medihome.nc"],
        "logo_text": "MEDIHOME",
        "badge_color": "sky",
    },
    {
        "id": "profil_immo",
        "name": "Profil Immo",
        "aliases": ["profil immo", "profilimmo"],
        "website": "https://www.profilimmo.nc",
        "city": "Nouméa",
        "domains": ["profilimmo.nc"],
        "logo_text": "PROFIL IMMO",
        "badge_color": "amber",
    },
    {
        "id": "lange_immo",
        "name": "Lange Immo",
        "aliases": ["lange immo", "langeimmo"],
        "website": "https://www.langeimmo.nc",
        "city": "Nouméa",
        "domains": ["langeimmo.nc"],
        "logo_text": "LANGE",
        "badge_color": "blue",
    },
    {
        "id": "residence_immo",
        "name": "Résidence Immobilière",
        "aliases": ["résidence immobilière", "residence immobiliere"],
        "website": "https://www.residence-immobiliere.nc",
        "city": "Nouméa",
        "domains": ["residence-immobiliere.nc"],
        "logo_text": "RÉSIDENCE",
        "badge_color": "teal",
    },
    {
        "id": "yc_immo",
        "name": "YC Immobilier",
        "aliases": ["yc immobilier", "yc immo"],
        "website": "https://www.ycimmobilier.nc",
        "city": "Nouméa",
        "domains": ["ycimmobilier.nc"],
        "logo_text": "YC IMMO",
        "badge_color": "yellow",
    },
    {
        "id": "chatelin",
        "name": "Chatelin Immobilier",
        "aliases": ["chatelin immobilier", "chatelin", "chatelin.nc", "cabinet chatelin"],
        "website": "https://www.chatelin.nc",
        "city": "Nouméa",
        "phone": "+687 289.888",
        "domains": ["chatelin.nc", "chatelin-immobilier.nc"],
        "logo_text": "CHATELIN",
        "badge_color": "cyan",
    },
    {
        "id": "particulier",
        "name": "Particuliers & Mandataires NC",
        "aliases": ["particulier", "particulier nc", "propriétaire"],
        "website": "https://www.immobilier.nc",
        "city": "Nouvelle-Calédonie",
        "domains": ["gmail.com", "yahoo.fr", "hotmail.com", "lagoon.nc", "canl.nc"],
        "logo_text": "PARTICULIER",
        "badge_color": "slate",
    }
]


def resolve_agency_name(raw_name: Optional[str], raw_mail: Optional[str] = None, text_blob: Optional[str] = None) -> str:
    """
    Associe un nom brut, email ou texte de description à l'une des agences calédoniennes officielles.
    Si aucune correspondance n'est trouvée, conserve le nom brut ou 'Particulier NC'.
    """
    clean_name = (raw_name or "").strip()
    clean_mail = (raw_mail or "").strip().lower()
    clean_blob = (text_blob or "").strip().lower()

    # 1. Vérification par domaine email
    if clean_mail:
        domain = clean_mail.split("@")[-1] if "@" in clean_mail else ""
        for ag in NC_AGENCIES:
            if ag["id"] == "particulier":
                continue
            for dom in ag["domains"]:
                if dom in domain:
                    return ag["name"]

    # 2. Vérification par nom direct ou alias
    if clean_name:
        name_lower = clean_name.lower()
        for ag in NC_AGENCIES:
            if ag["id"] == "particulier":
                continue
            for alias in ag["aliases"]:
                if alias in name_lower or name_lower in alias:
                    return ag["name"]

    # 3. Vérification dans le texte de l'annonce
    if clean_blob:
        for ag in NC_AGENCIES:
            if ag["id"] == "particulier":
                continue
            for alias in ag["aliases"]:
                if len(alias) >= 5 and re.search(rf"\b{re.escape(alias)}\b", clean_blob):
                    return ag["name"]

    if clean_name and clean_name != " ":
        return clean_name

    return "Particulier NC"


def get_all_agencies() -> List[Dict[str, Any]]:
    """Renvoie l'annuaire complet des agences avec métadonnées."""
    return list(NC_AGENCIES)
